In [ ]:
# Generate data 

In [1]:
import numpy as np
import pandas as pd

In [3]:
L,d_k,d_v = 4,8,8
q = np.random.randn(L,d_k)
k = np.random.randn(L,d_k)
v = np.random.randn(L,d_v)

In [4]:
print("Q\n", q)
print("K\n", k)
print("V\n", v)

Q
 [[-0.39016285 -1.45648506 -0.10617135 -0.98457274  1.6738831   1.07350769
  -1.03147667 -0.11664946]
 [-0.17982566  1.75143779  0.64756942 -0.33038926  0.51544228  0.29809899
  -0.52121047  2.49908179]
 [-1.18742707  1.22939348 -0.66472464  0.45360553 -1.71247761  0.63233327
  -0.01841373 -0.37131662]
 [-0.06930907 -1.8360792  -0.07275667  0.10454298  0.82059221  0.35010735
   0.27260064  0.87186854]]
K
 [[ 0.52263157 -0.32144937 -0.77657191  0.46122232  2.19498537  0.86811147
  -0.56536356 -2.47310449]
 [-0.1738152  -0.02770686 -1.94517592 -0.92254518  0.13092052 -0.77349685
  -0.53359773  1.62536351]
 [-0.65811429 -0.97566369 -0.59000385  0.53210294 -0.99547651  0.07922379
   0.21295433  0.5478917 ]
 [ 0.7739937  -0.97836579 -1.27620424  1.20481853 -1.07059201  0.74941952
   0.41950362 -0.56895926]]
V
 [[ 1.55121153  0.14766504  0.73439362  1.4901071   0.1279855  -0.02437641
  -0.47969517  1.04089687]
 [ 1.65878989  1.02413962 -0.22289342 -1.50092747  1.1603318  -0.76421869
   0.2

In [5]:
# Self Attention: Softmax 

In [6]:
np.matmul(q,k.T)

array([[ 5.37033643,  0.97259233, -0.64827387, -1.28162127],
       [-5.80789384,  3.20482859, -1.37959999, -5.04617328],
       [-2.57156744, -0.26014018,  1.76300756,  1.7837663 ],
       [ 0.45348138,  1.21626751,  1.68216103,  0.96367708]])

In [8]:
q.var(),k.var(),np.matmul(q,k.T).var()

(0.9595193273778149, 0.9603671051277238, 7.601385270379698)

In [11]:
import math
scaled = np.matmul(q,k.T)/math.sqrt(d_k)
q.var(),k.var(),scaled.var()

(0.9595193273778149, 0.9603671051277238, 0.950173158797462)

In [12]:
scaled

array([[ 1.89870066,  0.34386332, -0.22919942, -0.45312155],
       [-2.05340056,  1.13307801, -0.48776225, -1.78409167],
       [-0.90918639, -0.09197344,  0.6233173 ,  0.63065662],
       [ 0.16032988,  0.4300155 ,  0.59473374,  0.3407113 ]])

In [14]:
# Masking
mask = np.tril(np.ones((L,L)))
mask

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])